'use client'

import { FormEvent, useState } from 'react'
import { ArrowRightLeft, BookOpenCheck, Languages, Loader2, Sparkles, X } from 'lucide-react'

const LANGUAGES = [
  { code: 'ar', label: 'العربية', short: 'AR' }, { code: 'en', label: 'English', short: 'EN' }, { code: 'fr', label: 'Français', short: 'FR' },
  { code: 'es', label: 'Español', short: 'ES' }, { code: 'it', label: 'Italiano', short: 'IT' }, { code: 'de', label: 'Deutsch', short: 'DE' }, { code: 'pt', label: 'Português', short: 'PT' },
]
const SAVED_VOCABULARY_KEY = 'juba_lisan_saved_vocabulary'
function languageLabel(code: string) { if (code === 'auto') return 'Auto detect'; return LANGUAGES.find((language) => language.code === code)?.label ?? code.toUpperCase() }

export function VisitorTranslator() {
  const [open, setOpen] = useState(false); const [text, setText] = useState(''); const [source, setSource] = useState('auto'); const [target, setTarget] = useState('ar'); const [translation, setTranslation] = useState(''); const [loading, setLoading] = useState(false); const [error, setError] = useState(''); const [saved, setSaved] = useState(false)
  async function translate(event?: FormEvent) { event?.preventDefault(); if (!text.trim()) return; setLoading(true); setError(''); setSaved(false); try { const response = await fetch('/api/translate', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ text, source, target }) }); const data = await response.json(); if (!response.ok) throw new Error(data?.error || 'Translation failed'); setTranslation(data.translation) } catch (err) { setTranslation(''); setError(err instanceof Error ? err.message : 'Translation failed') } finally { setLoading(false) } }
  function saveToLearning() { if (!text.trim() || !translation.trim()) return; try { const existing = JSON.parse(localStorage.getItem(SAVED_VOCABULARY_KEY) || '[]'); const item = { id: `${Date.now()}-${Math.random().toString(36).slice(2, 8)}`, sourceText: text.trim(), translation: translation.trim(), sourceLanguage: source, targetLanguage: target, createdAt: new Date().toISOString(), mastery: 0, nextReviewAt: new Date().toISOString() }; const duplicate = existing.some((entry: { sourceText?: string; targetLanguage?: string }) => entry.sourceText?.toLowerCase() === item.sourceText.toLowerCase() && entry.targetLanguage === item.targetLanguage); if (!duplicate) localStorage.setItem(SAVED_VOCABULARY_KEY, JSON.stringify([item, ...existing].slice(0, 500))); setSaved(true) } catch { setError('This browser could not save the word for learning.') } }
  function swapLanguages() { if (source === 'auto') return; setSource(target); setTarget(source); setTranslation(''); setSaved(false) }
  return <>
    <button type="button" onClick={() => setOpen(true)} aria-label="Open instant translator" className="fixed bottom-5 end-5 z-40 inline-flex items-center gap-2 rounded-full border-2 border-[var(--juba-border)] bg-[var(--juba-accent)] px-5 py-3 text-sm font-black text-[var(--juba-text)] shadow-[var(--juba-shadow-md)] transition hover:-translate-y-1 hover:shadow-[var(--juba-shadow-lg)]"><Languages className="h-4 w-4" />Translate</button>
    {open && <div className="fixed inset-0 z-50 flex items-center justify-center overflow-y-auto bg-black/45 p-3 backdrop-blur-md sm:p-6"><div role="dialog" aria-modal="true" aria-labelledby="visitor-translator-title" className="w-full max-w-5xl overflow-hidden rounded-[32px] border-2 border-[var(--juba-border)] bg-[var(--juba-surface)] shadow-[var(--juba-shadow-lg)]">
      <div className="flex items-start justify-between border-b-2 border-[var(--juba-border)] p-5 sm:p-8"><div><div className="mb-3 inline-flex items-center gap-2 rounded-full border border-[var(--juba-border)] bg-[var(--juba-accent)] px-3 py-1 text-[10px] font-black uppercase tracking-[.16em]"><Sparkles className="h-3 w-3" />JUBA LISAN</div><h2 id="visitor-translator-title" className="text-3xl font-black tracking-tight text-[var(--juba-text)] sm:text-4xl">Instant translator</h2><p className="mt-2 max-w-xl text-sm font-medium text-[var(--juba-muted)]">Translate first. Then turn what you use into something you learn.</p></div><button type="button" onClick={() => setOpen(false)} aria-label="Close translator" className="rounded-full border-2 border-[var(--juba-border)] bg-[var(--juba-surface-2)] p-2 text-[var(--juba-text)] transition hover:-rotate-6"><X className="h-5 w-5" /></button></div>
      <form onSubmit={translate} className="p-4 sm:p-7"><div className="grid gap-3 lg:grid-cols-[1fr_auto_1fr] lg:items-stretch">
        <section className="flex min-h-[300px] flex-col rounded-[26px] border-2 border-[var(--juba-border)] bg-[var(--juba-surface-2)] p-4 sm:p-5"><div className="mb-4 flex items-center gap-2"><span className="rounded-full bg-[var(--juba-text)] px-3 py-1.5 text-[11px] font-black uppercase text-[var(--juba-surface)]">From</span><select value={source} onChange={(e) => { setSource(e.target.value); setTranslation(''); setSaved(false) }} className="rounded-full border border-[var(--juba-border)] bg-[var(--juba-surface)] px-3 py-1.5 text-sm font-bold text-[var(--juba-text)] outline-none"><option value="auto">Auto detect</option>{LANGUAGES.map((l) => <option key={l.code} value={l.code}>{l.label}</option>)}</select></div><textarea value={text} onChange={(e) => { setText(e.target.value); setSaved(false) }} maxLength={2000} rows={7} autoFocus placeholder="Type or paste your text here…" className="min-h-[190px] flex-1 resize-none bg-transparent text-xl font-semibold leading-relaxed text-[var(--juba-text)] outline-none placeholder:text-[var(--juba-muted)]" /><div className="mt-3 flex justify-between text-xs font-semibold text-[var(--juba-muted)]"><span>{text.length}/2000</span><span>{source === 'auto' ? 'Automatic detection' : languageLabel(source)}</span></div></section>
        <div className="flex items-center justify-center"><button type="button" onClick={swapLanguages} disabled={source === 'auto'} aria-label="Swap languages" className="rounded-full border-2 border-[var(--juba-border)] bg-[var(--juba-accent)] p-3 shadow-[var(--juba-shadow-sm)] transition hover:rotate-180 disabled:opacity-35"><ArrowRightLeft className="h-5 w-5" /></button></div>
        <section className="flex min-h-[300px] flex-col rounded-[26px] border-2 border-[var(--juba-border)] bg-[var(--juba-accent)] p-4 sm:p-5"><div className="mb-4 flex items-center gap-2"><span className="rounded-full bg-[var(--juba-text)] px-3 py-1.5 text-[11px] font-black uppercase text-[var(--juba-surface)]">To</span><select value={target} onChange={(e) => { setTarget(e.target.value); setTranslation(''); setSaved(false) }} className="rounded-full border border-black/20 bg-white/60 px-3 py-1.5 text-sm font-bold text-neutral-950 outline-none">{LANGUAGES.map((l) => <option key={l.code} value={l.code}>{l.label}</option>)}</select></div><div className="flex flex-1 items-start">{error ? <p className="text-sm font-bold text-red-700">{error}</p> : translation ? <div className="w-full"><p className="text-xl font-black leading-relaxed text-neutral-950 sm:text-2xl">{translation}</p><button type="button" onClick={saveToLearning} className="mt-5 inline-flex items-center gap-2 rounded-full border-2 border-neutral-950 bg-white px-4 py-2.5 text-sm font-black text-neutral-950 shadow-[3px_3px_0_rgba(17,17,17,.85)] transition hover:-translate-y-0.5"><BookOpenCheck className="h-4 w-4" />{saved ? 'Saved for learning ✓' : 'Learn this word'}</button></div> : <p className="text-lg font-semibold text-neutral-700/70">Your translation will appear here.</p>}</div><div className="mt-3 text-xs font-black uppercase tracking-wider text-neutral-950/55">{languageLabel(target)}</div></section>
      </div><div className="mt-5 flex flex-col-reverse gap-3 sm:flex-row sm:items-center sm:justify-between"><p className="text-xs font-semibold leading-relaxed text-[var(--juba-muted)]">Translate → save → learn → review.</p><button type="submit" disabled={!text.trim() || loading} className="inline-flex min-h-12 items-center justify-center gap-2 rounded-full border-2 border-[var(--juba-border)] bg-[var(--juba-text)] px-7 py-3 text-sm font-black text-[var(--juba-surface)] shadow-[4px_4px_0_var(--juba-accent)] transition hover:-translate-y-0.5 disabled:opacity-45">{loading ? <Loader2 className="h-4 w-4 animate-spin" /> : <Languages className="h-4 w-4" />}{loading ? 'Translating…' : 'Translate'}</button></div></form>
    </div></div>}
  </>
}
