import { useTranslations } from 'next-intl'
import type { ConvStatus } from './StatusIndicator'
interface Props { status: ConvStatus; sessionActive?: boolean; onStart: () => void; onStop: () => void }
export default function MicButton({ status, onStart, onStop }: Props) {
  const t = useTranslations('conversation')
  if (status === 'loading' || status === 'warming' || status === 'connecting') return <button disabled className="flex h-[52px] w-[52px] items-center justify-center rounded-full border border-[var(--duo-line)] bg-[var(--duo-card)] opacity-60 shadow-sm" aria-label={t(status === 'loading' ? 'statusLoading' : status === 'warming' ? 'statusWarming' : 'statusConnecting')}><span className="animate-pulse text-base text-[var(--duo-green)]">○</span></button>
  if (status === 'ready') return <button onClick={onStart} className="rounded-[9px] border border-[var(--duo-green)] bg-[var(--duo-green)] px-6 py-2.5 text-[0.7rem] font-bold tracking-wide text-white uppercase shadow-sm transition-all hover:-translate-y-px hover:bg-[var(--duo-green-dark)] hover:shadow-md focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--duo-green)]/30">{t('start')}</button>
  if (status === 'live') return <button onClick={onStop} className="group flex h-[52px] w-[52px] items-center justify-center rounded-full border border-[var(--duo-red)]/30 bg-[var(--duo-card)] shadow-sm transition-all hover:bg-[color-mix(in_srgb,var(--duo-red)_8%,transparent)] hover:shadow-md focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--duo-red)]/30" aria-label={t('stop')} title={t('stop')}><span className="text-sm text-[var(--duo-red)] transition-transform group-hover:scale-110">■</span></button>
  return <button onClick={onStart} className="rounded-[9px] border border-[var(--duo-line)] bg-[var(--duo-card)] px-6 py-2.5 text-[0.7rem] font-semibold tracking-wide text-[var(--duo-muted)] shadow-sm transition-all hover:-translate-y-px hover:border-[var(--duo-green)] hover:text-[var(--duo-green-dark)] hover:shadow-md focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--duo-green)]/20 uppercase">{t('startNew')}</button>
}