import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react'
import { EducationalGameSession } from './EducationalGameSession'

const {start, answer, complete, setProgress, markUpdated} = vi.hoisted(() => ({start:vi.fn(),answer:vi.fn(),complete:vi.fn(),setProgress:vi.fn(),markUpdated:vi.fn()}))
vi.mock('@/lib/games/persist', () => ({startGameSession:start,answerGameSessionQuestion:answer,completeGameSession:complete}))
vi.mock('@/store/progress', () => ({useProgressStore:{getState:() => ({streak:2,setProgress})}}))
vi.mock('@/lib/learning-progress', () => ({markLearningProgressUpdated:markUpdated}))
const question = {id:'q1',prompt:'Choose the meaning',choices:['correct','wrong'],hint:'Read the definition carefully.',skill:'vocabulary',difficulty:1,input_mode:'choice'}
const session = {session_id:'s1',questions:[question],daily_challenge:false,daily_challenge_date:''}
const result = {round_correct:1,round_questions:1,xp_earned:15,total_xp:115,skills:{vocabulary:0.4},achievements:[],games_played:1,questions_answered:1,correct_answers:1,best_round_score:100,daily_challenges_completed:0,last_daily_challenge_date:'',current_correct_streak:1,best_correct_streak:1,new_achievements:[]}
const props = {gameId:'quick_choice' as const,language:'en' as const,targetLanguage:'en-GB',difficulty:1,arabic:false,title:'Meaning hunt',onExit:vi.fn(),onReplay:vi.fn()}
beforeEach(() => {vi.clearAllMocks();start.mockResolvedValue(session);complete.mockResolvedValue(result)})
afterEach(() => {cleanup();vi.useRealTimers()})

describe('Real game session engine', () => {
  it('uses the server-issued next question instead of indexing an absent five-question array', async () => {
    answer.mockResolvedValue({correct:true,answered:1,total:5,finished:false,question:{...question,id:'q2',prompt:'A new server question'}})
    render(<EducationalGameSession {...props} />)
    fireEvent.click(await screen.findByRole('button',{name:'1 correct'}))
    await screen.findByText('Correct!')
    fireEvent.click(screen.getByRole('button',{name:'Next'}))
    await screen.findByText('A new server question')
    expect(answer).toHaveBeenCalledWith('s1','q1','correct')
    expect(complete).not.toHaveBeenCalled()
  })
  it('retries the same logical item and submits one successful answer per ID', async () => {
    answer.mockResolvedValueOnce({correct:false,answered:0,total:1,finished:false,question:{...question,prompt:'Try the same item again'}}).mockResolvedValueOnce({correct:true,answered:1,total:1,finished:true,question:null})
    render(<EducationalGameSession {...props} />)
    fireEvent.click(await screen.findByRole('button',{name:'2 wrong'}))
    await screen.findByText('Not quite. We’ll revisit this item.')
    fireEvent.click(screen.getByRole('button',{name:'Try again'}))
    await screen.findByText('Try the same item again')
    fireEvent.click(screen.getByRole('button',{name:'1 correct'}))
    await screen.findByText('Correct!')
    fireEvent.click(screen.getByRole('button',{name:'Save round'}))
    await screen.findByText('Round saved')
    expect(complete).toHaveBeenCalledWith('s1',[{question_id:'q1',choice:'correct'}],false,'',[])
    expect(setProgress).toHaveBeenCalledWith(expect.objectContaining({xp:115}))
    expect(markUpdated).toHaveBeenCalledTimes(1)
  })
  it('keeps the round and retries saving after a rejected completion', async () => {
    answer.mockResolvedValue({correct:true,answered:1,total:1,finished:true,question:null})
    complete.mockRejectedValueOnce(new Error('network')).mockResolvedValueOnce(result)
    render(<EducationalGameSession {...props} />)
    fireEvent.click(await screen.findByRole('button',{name:'1 correct'}))
    await screen.findByText('Correct!')
    fireEvent.click(screen.getByRole('button',{name:'Save round'}))
    await screen.findByRole('alert')
    expect(screen.queryByText('Round saved')).toBeNull()
    expect(markUpdated).not.toHaveBeenCalled()
    fireEvent.click(screen.getByRole('button',{name:'Save round'}))
    await screen.findByText('Round saved')
    expect(complete).toHaveBeenCalledTimes(2)
  })
  it('sends only one answer while validation is pending', async () => {
    let resolve!: (value:unknown) => void
    answer.mockReturnValue(new Promise(value => {resolve=value}))
    render(<EducationalGameSession {...props} />)
    const button=await screen.findByRole('button',{name:'1 correct'})
    fireEvent.click(button);fireEvent.click(button)
    expect(answer).toHaveBeenCalledTimes(1)
    resolve({correct:true,answered:1,total:1,finished:true,question:null})
    await screen.findByText('Correct!')
  })
  it('validates matching pairs and preserves actual missed moves in the submitted trace', async () => {
    start.mockResolvedValue({...session,questions:[],interaction:{type:'matching',left:[{id:'l1',label:'apple',pair_key:'a'},{id:'l2',label:'book',pair_key:'b'}],right:[{id:'r2',label:'pages',pair_key:'b'},{id:'r1',label:'fruit',pair_key:'a'}]}})
    render(<EducationalGameSession {...props} gameId="matching" />)
    fireEvent.click(await screen.findByRole('button',{name:'apple'}))
    fireEvent.click(screen.getByRole('button',{name:'pages'}))
    await screen.findByText('That meaning does not match. Try again.')
    fireEvent.click(screen.getByRole('button',{name:'apple'}))
    fireEvent.click(screen.getByRole('button',{name:'fruit'}))
    fireEvent.click(screen.getByRole('button',{name:'book'}))
    fireEvent.click(screen.getByRole('button',{name:'pages'}))
    fireEvent.click(await screen.findByRole('button',{name:'Save round'}))
    await screen.findByText('Round saved')
    expect(complete).toHaveBeenCalledWith('s1',[],false,'',[{left:'l1',right:'r2'},{left:'l1',right:'r1'},{left:'l2',right:'r2'}])
  })
  it('submits the learner sentence order rather than assuming the shuffled tiles are the answer', async () => {
    start.mockResolvedValue({...session,questions:[],interaction:{type:'ordering',items:[{id:'b',label:'learn'},{id:'a',label:'I'}]}})
    complete.mockResolvedValue({...result,round_correct:0,xp_earned:0})
    render(<EducationalGameSession {...props} gameId="sentence_builder" />)
    fireEvent.click(await screen.findByRole('button',{name:'I'}))
    fireEvent.click(screen.getByRole('button',{name:'learn'}))
    fireEvent.click(screen.getByRole('button',{name:'Score and save sentence'}))
    await screen.findByText('Round saved')
    expect(complete).toHaveBeenCalledWith('s1',[],false,'',[{order:['a','b']}])
    expect(screen.getByText('0/1 correct · +0 XP')).toBeTruthy()
  })
  it('shows a start failure without rendering a pretend challenge', async () => {
    start.mockRejectedValue(new Error('no active plan'))
    render(<EducationalGameSession {...props} />)
    await screen.findByRole('alert')
    expect(screen.getByRole('button',{name:'Retry'})).toBeTruthy()
    expect(screen.queryByText('Choose the meaning')).toBeNull()
  })
  it('does not write stale results after the learner leaves the game', async () => {
    let resolve!: (value:unknown) => void
    answer.mockResolvedValue({correct:true,answered:1,total:1,finished:true,question:null})
    complete.mockReturnValue(new Promise(value => {resolve=value}))
    const view = render(<EducationalGameSession {...props} />)
    fireEvent.click(await screen.findByRole('button',{name:'1 correct'}))
    await screen.findByText('Correct!')
    fireEvent.click(screen.getByRole('button',{name:'Save round'}))
    await waitFor(() => expect(complete).toHaveBeenCalledTimes(1))
    view.unmount();resolve(result)
    await Promise.resolve();await Promise.resolve()
    expect(setProgress).not.toHaveBeenCalled()
  })
})
