#!/usr/bin/env python3
"""Install the verified JUBA Nunito/Cairo package without network or dependencies."""
import argparse
import hashlib
from pathlib import Path
import struct
import sys
import zipfile

HASHES = {
    'Cairo-Variable.woff2': 'f5a0d0c519337815aeb2b2954722aeb8a678e1c3bd49ed080e8ea4a003e53b18',
    'Nunito-Regular-Variable.woff2': 'bebb71136ea9a7144ed4d3b90054fd5488e66dc4e5814a4d45a04c60fa9b3656',
    'Nunito-Italic-Variable.woff2': '9154282c74e3111dcada62363384aa36b68f325c9c9adaf579674e7335c4b00d',
}
LICENSES = ('Cairo-OFL.txt', 'Nunito-OFL.txt')
CSS = '''/* Generated by install_local_fonts.py after binary verification. No remote or OS-local font source. */
@font-face{font-family:"JUBA Nunito Local";src:url("/fonts/Nunito-Regular-Variable.woff2") format("woff2");font-weight:200 1000;font-style:normal;font-display:swap;}
@font-face{font-family:"JUBA Nunito Local";src:url("/fonts/Nunito-Italic-Variable.woff2") format("woff2");font-weight:200 1000;font-style:italic;font-display:swap;}
@font-face{font-family:"JUBA Cairo Local";src:url("/fonts/Cairo-Variable.woff2") format("woff2");font-weight:200 1000;font-style:normal;font-display:swap;}
@font-face{font-family:"JUBA Cairo Local";src:url("/fonts/Cairo-Variable.woff2") format("woff2");font-weight:200 1000;font-style:oblique -11deg 11deg;font-display:swap;}
/* Extra selector specificity defeats legacy Arial-only Dashboard overrides. */
html[lang] :is(.juba-app-shell,.juba-landing-refresh){font-family:"JUBA Nunito Local","JUBA Cairo Local",system-ui,sans-serif!important;}
html[lang="ar"] :is(.juba-app-shell,.juba-landing-refresh),html[lang] :is(.juba-app-shell,.juba-landing-refresh)[dir="rtl"]{font-family:"JUBA Cairo Local","JUBA Nunito Local",system-ui,sans-serif!important;}
html[lang] :is(.juba-app-shell,.juba-landing-refresh) :is(h1,h2,h3,h4,h5,h6,button,a,input,textarea,select){font-family:inherit;}
'''
IMPORT = "import './(app)/nunito-local.css'"


def verify_font(name, data):
    if hashlib.sha256(data).hexdigest() != HASHES[name]:
        raise ValueError(f'{name}: SHA-256 mismatch. Use the supplied combined font package.')
    if len(data) < 48 or data[:4] != b'wOF2' or struct.unpack('>I', data[8:12])[0] != len(data):
        raise ValueError(f'{name}: invalid WOFF2 header/length')


def load_package(path):
    with zipfile.ZipFile(path) as archive:
        names = archive.namelist()
        required = list(HASHES) + list(LICENSES)
        if any(names.count(name) != 1 for name in required):
            raise ValueError('Package must contain exactly one copy of each required font and license at its root.')
        contents = {}
        # Never extract arbitrary entries or trust an archive-supplied CSS/script.
        for name in required:
            if archive.getinfo(name).file_size > 2_000_000:
                raise ValueError('Oversized archive member')
            contents[name] = archive.read(name)
        for name in HASHES:
            verify_font(name, contents[name])
        for name in LICENSES:
            text = contents[name].decode('utf-8')
            if 'SIL OPEN FONT LICENSE' not in text or 'Version 1.1' not in text:
                raise ValueError(f'{name}: missing OFL 1.1 license')
        return contents


def install(root, package=None, check=False):
    root = Path(root).resolve()
    layout = root / 'frontend/src/app/layout.tsx'
    css_path = root / 'frontend/src/app/(app)/nunito-local.css'
    target = root / 'frontend/public/fonts'
    if not layout.is_file() or not css_path.is_file():
        raise ValueError('Repository layout not found. Pass --repo-root with the project directory.')
    old_layout = layout.read_text(encoding='utf-8')
    if check:
        for name in HASHES:
            verify_font(name, (target / name).read_bytes())
        for name in LICENSES:
            if not (target / name).is_file():
                raise ValueError(f'Missing license: {name}')
        if css_path.read_text(encoding='utf-8') != CSS or IMPORT not in old_layout:
            raise ValueError('Local font CSS or root import does not match the installer.')
        return 'PASS: installed font hashes, WOFF2 headers, licenses, CSS and root import.'
    if package is None:
        raise ValueError('Supply the combined JUBA-Nunito-Cairo-local-fonts.zip package.')
    contents = load_package(package)
    if IMPORT in old_layout:
        new_layout = old_layout
    elif "import './globals.css'" in old_layout:
        new_layout = old_layout.replace("import './globals.css'", "import './globals.css'\n" + IMPORT, 1)
    else:
        raise ValueError('Root CSS import changed; stopped without modifying files.')
    # Preflight every destination before writing. Never overwrite a different binary.
    for name, data in contents.items():
        destination = target / name
        if destination.exists() and destination.read_bytes() != data:
            raise ValueError(f'Existing {name} differs; stopped without modifying files.')
    target.mkdir(parents=True, exist_ok=True)
    for name, data in contents.items():
        (target / name).write_bytes(data)
    css_path.write_text(CSS, encoding='utf-8')
    layout.write_text(new_layout, encoding='utf-8')
    return install(root, check=True)


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('package', nargs='?', type=Path)
    parser.add_argument('--repo-root', type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args(argv)
    try:
        print(install(args.repo_root, args.package, args.check))
        return 0
    except (ValueError, OSError, zipfile.BadZipFile) as exc:
        print(f'Font setup stopped: {exc}', file=sys.stderr)
        return 1


if __name__ == '__main__':
    raise SystemExit(main())
